# -*- mode: ruby -*-
# vi: set ft=ruby :

$script = <<-SCRIPT
    echo I am provisioning...
    date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure(2) do |config|

    config.vm.box = "hashicorp/precise64"
  
    config.vm.network "private_network", ip: "55.55.55.5"

    config.vm.provision "shell", inline: $script

    config.vm.provision "file", source: "Vagrantfile", destination: "$HOME"
  
  end
  
  