# -*- mode: ruby -*-
# vi: set ft=ruby :

servers=[
  {
    :hostname => "web",
    :ip => "192.168.100.10",
    :box => "hashicorp/precise64",
    :ram => 1024,
    :cpu => 2,
    :provision => "sudo apt-get update -y && sudo apt-get install -y apache2"
  },
  {
    :hostname => "db",
    :ip => "192.168.100.11",
    :box => "hashicorp/precise64",
    :ram => 1024,
    :cpu => 2,
    :provision => "sudo apt-get update -y && sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password root' && sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root' && sudo apt-get -y install mysql-server "
  }
]

Vagrant.configure(2) do |config|
    servers.each do |machine|
        config.vm.define machine[:hostname] do |node|
            node.vm.box = machine[:box]
            node.vm.hostname = machine[:hostname]
            node.vm.provision "shell", inline: machine[:provision]
            node.vm.network "private_network", ip: machine[:ip]
            node.vm.provider "virtualbox" do |vb|
                vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
           end
       end 
   end
end