# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    config.vm.provider "virtualbox"
    config.vm.box = "bento/centos-7.1"
    config.vm.network "private_network", ip: "55.55.55.150"
    config.vm.synced_folder ".", "/home/vagrant/shared/"
    config.vm.provision "shell", inline: <<-SHELL    
      sudo yum update -y     
      sudo yum install -y wget
      sudo yum install -y curl
      sudo yum install -y vim
      sudo yum install -y git    
      sudo yum install -y build-essential
      sudo yum install -y unzip 
      #
      # Install PIP
      #
      sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
      sudo python get-pip.py
      sudo pip install packaging
      #
      # Install Ansible
      #
      sudo yum -y install python-jinja2 python-paramiko PyYAML make MySQL-python
      sudo pip install ansible
      sudo echo "[localhost]" > ~/ansible_hosts
      sudo echo "localhost ansible_connection=local" >> ~/ansible_hosts
      sudo echo "export ANSIBLE_INVENTORY=~/ansible_hosts" >> ~/.bashrc
    SHELL
  
  end

  